version: '3'

services:
  ispan1:
    # image: quay.io/infinispan/server:latest
    image: infinispan/server:latest
    container_name: ispan1
    hostname: ispan1
    restart: always
    user: $JBOSS_UID:$JBOSS_GID
    environment:
      - USER=admin
      - PASS=password
    # command:
    #   - --cluster-name=ISPN
    ports:
      - "11222:11222"
    volumes:
      - "./ispan-conf/ispan1-14/infinispan.xml:/opt/infinispan/server/conf/infinispan.xml"
    networks:
      keycloak_ispan_net:
        ipv4_address: 172.10.0.98

  ispan2:
    # image: quay.io/infinispan/server:latest
    image: infinispan/server:latest
    container_name: ispan2
    hostname: ispan2
    restart: always
    user: $JBOSS_UID:$JBOSS_GID
    environment:
      - USER=admin
      - PASS=password
    # command:
    #   - --cluster-name=ISPN
    ports:
      - "11223:11222"
    volumes:
      - "./ispan-conf/ispan2-14/infinispan.xml:/opt/infinispan/server/conf/infinispan.xml"
    networks:
      keycloak_ispan_net:
        ipv4_address: 172.10.0.99

  keycloak:
    build:
      context: .
      dockerfile: ./keycloak/Dockerfile
    container_name: keycloak
    tty: true
    stdin_open: true
    restart: always
    user: $UID:$GID
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # env_file: ./.env.keycloak
    volumes:
      - ./keycloak/conf:/opt/keycloak/conf
      - ./keycloak/ssl:/opt/keycloak/ssl
    command:
      - "start"
    ports:
      - 8080:8080
      - 8443:8443
      - 7800:7800
    networks:
      keycloak_ispan_net:
        ipv4_address: 172.10.0.3

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "55432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      keycloak_ispan_net:
        ipv4_address: 172.10.0.4

networks:

  keycloak_ispan_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24